# Generated by Django 5.2.1 on 2025-05-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="carousel/")),
                (
                    "animation_direction",
                    models.CharField(
                        choices=[("Left", "fadeInLeft"), ("Right", "fadeInRight")],
                        default="Right",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
