# Generated by Django 5.2.1 on 2025-06-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMININGapp', '0002_aboutsection_alter_carousel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='button_link',
        ),
    ]
