# Generated by Django 5.2.1 on 2025-06-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMININGapp', '0003_remove_aboutsection_button_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSection',
        ),
    ]
