# Generated by Django 5.2.1 on 2025-06-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMININGapp', '0004_delete_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('rating', models.IntegerField(default=5)),
                ('image_url', models.URLField()),
                ('short_description', models.TextField()),
                ('delay', models.CharField(default='.3s', max_length=10)),
                ('modal_target', models.CharField(default='#', max_length=50)),
            ],
        ),
    ]
