# Generated by Django 5.2.1 on 2025-06-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMININGapp', '0006_remove_course_image_url_course_iimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('exercises', models.PositiveIntegerField()),
                ('duration', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=50)),
                ('learners', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='modal_images/')),
                ('modal_id', models.CharField(help_text='E.g. modalPython, modalPowerBI', max_length=100)),
            ],
        ),
    ]
