# Generated by Django 5.2.1 on 2025-06-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMININGapp', '0007_coursemodal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodal',
            name='image',
            field=models.ImageField(upload_to='static/modals/'),
        ),
    ]
