# Generated by Django 5.2.1 on 2025-06-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMININGapp', '0008_alter_coursemodal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodal',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
