# Generated by Django 5.2.1 on 2025-06-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMININGapp', '0010_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='static/testimonials/'),
        ),
    ]
