# Generated by Django 5.2.1 on 2025-06-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMININGapp', '0011_alter_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('address_link', models.URLField(help_text='Google Maps embed link')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('map_embed_url', models.URLField(help_text='Google Map iframe src')),
            ],
        ),
    ]
