# Generated by Django 5.2.1 on 2025-06-04 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DMININGapp', '0012_contactinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='map_embed_url',
        ),
    ]
