# Generated by Django 5.2.1 on 2025-06-06 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DMININGapp', '0014_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
